### ISSUE TITLE
Mounting an engine raises violations

### ISSUE THREAD

**Issue by Spence1115** [Shopify/packwerk#246]
**Description**
When I mount an engine in the main app for the purposes of accessing the API, I receive violations from `packwerk check`

```bash
Privacy violation: '::SomeService::Engine' is private to 'modules/some_service' but referenced from '.'.
Is there a public entrypoint in 'modules/some_service/public/' that you can use instead?
```

Am I missing something in terms of how we should be accessing our engines?

**To Reproduce**
```ruby
# ~/config/routes.rb

Rails.application.routes.draw do
  mount SomeService::Engine, at: "/some_service"
end
```

```yml
# ~/package.yml

enforce_dependencies: true
enforce_privacy: false
dependencies:
- "modules/some_service"
```
